<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-MauiBlazorWeb_Web-2278722e-a7bf-4115-9b71-8d47644177e7</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Components\Layout\NavMenu.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Components\Layout\NavMenu.razor.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1" />
    <PackageReference Include="NSwag.AspNetCore" Version="14.6.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MauiBlazorWeb.ServiceDefaults\MauiBlazorWeb.ServiceDefaults.csproj" />
    <ProjectReference Include="..\MauiBlazorWeb.Shared\MauiBlazorWeb.Shared.csproj" />
  </ItemGroup>

</Project>
